currentDeployment: default
deploymentConfigurations:
- name: default
  version: 1.11.2
  providers:
    appengine:
      enabled: false
      accounts: []
    aws:
      enabled: false
      accounts: []
      bakeryDefaults:
        baseImages: []
      defaultKeyPairTemplate: '{{name}}-keypair'
      defaultRegions:
      - name: us-west-2
      defaults:
        iamRole: BaseIAMRole
    ecs:
      enabled: false
      accounts: []
    azure:
      enabled: false
      accounts: []
      bakeryDefaults:
        templateFile: azure-linux.json
        baseImages: []
    dcos:
      enabled: false
      accounts: []
      clusters: []
    google:
      enabled: false
      accounts: []
      bakeryDefaults:
        templateFile: gce.json
        baseImages: []
        zone: us-central1-f
        network: default
        useInternalIp: false
    dockerRegistry:
      enabled: true
      accounts:
      - name: my-docker-registry
        requiredGroupMembership: []
        providerVersion: V1
        permissions: {}
        address: https://index.docker.io
        username: opsmx11
        password: Networks123!
        email: fake.email@spinnaker.io
        cacheIntervalSeconds: 30
        clientTimeoutMillis: 60000
        cacheThreads: 1
        paginateSize: 100
        sortTagsByDate: false
        trackDigests: false
        insecureRegistry: false
        repositories:
        - opsmx11/ciscotest
        - opsmx11/restapp
      primaryAccount: my-docker-registry
    kubernetes:
      enabled: true
      accounts:
      - name: my-k8s-v2-account
        requiredGroupMembership: []
        providerVersion: V2
        permissions:
          WRITE:
          - mail-qa
        dockerRegistries:
        - accountName: my-docker-registry
          namespaces: []
        configureImagePullSecrets: true
        cacheThreads: 1
        namespaces: []
        omitNamespaces: []
        kinds: []
        omitKinds: []
        customResources: []
        cachingPolicies: []
        kubeconfigFile: /home/opsmxgcetest/.kube/config
        oauthScopes: []
        oAuthScopes: []
      - name: openshift-v2-account
        requiredGroupMembership: []
        providerVersion: V2
        permissions: {}
        dockerRegistries:
        - accountName: my-docker-registry
          namespaces: []
        configureImagePullSecrets: true
        cacheThreads: 1
        namespaces:
        - default
        - test1
        omitNamespaces: []
        kinds: []
        omitKinds: []
        customResources: []
        cachingPolicies: []
        kubeconfigFile: /home/opsmxgcetest/.kube/openshift/config
        oauthScopes: []
        oAuthScopes: []
      - name: gke-v2-account
        requiredGroupMembership: []
        providerVersion: V2
        permissions: {}
        dockerRegistries: []
        configureImagePullSecrets: true
        cacheThreads: 1
        namespaces: []
        omitNamespaces: []
        kinds: []
        omitKinds: []
        customResources: []
        cachingPolicies: []
        kubeconfigFile: /home/opsmxgcetest/.kube/opsmx-gke-config
        oauthScopes: []
        oAuthScopes: []
        onlySpinnakerManaged: false
      - name: my-k8s-v1-account
        requiredGroupMembership: []
        providerVersion: V1
        permissions: {}
        dockerRegistries:
        - accountName: my-docker-registry
          namespaces: []
        configureImagePullSecrets: true
        cacheThreads: 1
        namespaces: []
        omitNamespaces: []
        kinds: []
        omitKinds: []
        customResources: []
        cachingPolicies: []
        kubeconfigFile: /home/opsmxgcetest/.kube/op-op-config
        oauthScopes: []
        oAuthScopes: []
        onlySpinnakerManaged: false
      - name: opsmx-v2-opsmx-account
        requiredGroupMembership: []
        providerVersion: V2
        permissions: {}
        dockerRegistries: []
        configureImagePullSecrets: true
        cacheThreads: 1
        namespaces: []
        omitNamespaces: []
        kinds: []
        omitKinds: []
        customResources: []
        cachingPolicies: []
        kubeconfigFile: /home/opsmxgcetest/.kube/op-op-config
        oauthScopes: []
        oAuthScopes: []
        onlySpinnakerManaged: false
      primaryAccount: opsmx-v2-opsmx-account
    openstack:
      enabled: false
      accounts:
      - name: my-openstack-account
        environment: openstackenv
        requiredGroupMembership: []
        providerVersion: V1
        permissions: {}
        authUrl: http://10.142.0.4:5000/v3
        username: admin
        password: openstack
        projectName: admin
        domainName: Default
        insecure: true
        lbaas:
          pollTimeout: 60
          pollInterval: 5
        regions:
        - RegionOne
      primaryAccount: my-openstack-account
      bakeryDefaults:
        baseImages: []
    oracle:
      enabled: false
      accounts: []
      bakeryDefaults:
        templateFile: oci.json
        baseImages: []
  deploymentEnvironment:
    size: SMALL
    type: LocalDebian
    updateVersions: true
    consul:
      enabled: false
    vault:
      enabled: false
    customSizing: {}
    sidecars: {}
    initContainers: {}
    hostAliases: {}
    nodeSelectors: {}
    gitConfig:
      upstreamUser: spinnaker
    haServices:
      clouddriver:
        enabled: false
        disableClouddriverRoDeck: false
      echo:
        enabled: false
  persistentStorage:
    persistentStoreType: gcs
    azs: {}
    gcs:
      jsonPath: /home/opsmxgcetest/.gcp/gcp-account.json
      project: development-project-210505
      bucket: opsmx-demospinnaker
      rootFolder: front50
    redis: {}
    s3:
      bucket: spin-58daba87-645b-4111-a753-9c7747d54048
      rootFolder: front50
      region: us-west-1
      accessKeyId: AKIAILPQJWICLNRMQINA
      secretAccessKey: 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
    oracle: {}
  features:
    auth: false
    fiat: false
    chaos: false
    entityTags: false
    jobs: false
    pipelineTemplates: true
    artifacts: true
    mineCanary: true
  metricStores:
    datadog:
      enabled: false
      tags: []
    prometheus:
      enabled: true
      add_source_metalabels: true
    stackdriver:
      enabled: false
    period: 30
    enabled: true
  notifications:
    slack:
      enabled: false
  timezone: America/Los_Angeles
  ci:
    jenkins:
      enabled: true
      masters:
      - name: opsmx-jenkins-master
        address: http://35.211.30.238:8181/jenkins
        username: opsmx
        password: Bumblebee@123$
    travis:
      enabled: false
      masters: []
    wercker:
      enabled: false
      masters: []
  security:
    apiSecurity:
      ssl:
        enabled: false
      overrideBaseUrl: http://35.233.137.252:8084
    uiSecurity:
      ssl:
        enabled: false
      overrideBaseUrl: http://35.233.137.252:9000
    authn:
      oauth2:
        enabled: false
        client: {}
        resource: {}
        userInfoMapping: {}
      saml:
        enabled: false
      ldap:
        enabled: true
        url: ldap://35.227.87.101:389
        userDnPattern: CN={0},CN=Users,DC=local,DC=opsmx,DC=com
      x509:
        enabled: false
      iap:
        enabled: false
      enabled: true
    authz:
      groupMembership:
        service: EXTERNAL
        google:
          roleProviderType: GOOGLE
        github:
          roleProviderType: GITHUB
        file:
          roleProviderType: FILE
        ldap:
          roleProviderType: LDAP
      enabled: true
  artifacts:
    bitbucket:
      enabled: true
      accounts:
      - name: my-bitbucket-account
        username: sher-locked
        password: sher5!5LOCKED
    gcs:
      enabled: false
      accounts: []
    oracle:
      enabled: false
      accounts: []
    github:
      enabled: true
      accounts:
      - name: opsmx-restapp-account
        username: OpsMx
        password: Sreegun3214
    gitlab:
      enabled: false
      accounts: []
    http:
      enabled: false
      accounts: []
    helm:
      enabled: false
      accounts: []
    s3:
      enabled: false
      accounts: []
  pubsub:
    enabled: false
    google:
      enabled: false
      subscriptions: []
  canary:
    enabled: false
    serviceIntegrations:
    - name: google
      enabled: false
      accounts: []
      gcsEnabled: false
      stackdriverEnabled: false
    - name: prometheus
      enabled: false
      accounts: []
    - name: datadog
      enabled: false
      accounts: []
    - name: aws
      enabled: false
      accounts: []
      s3Enabled: false
    reduxLoggerEnabled: true
    defaultJudge: NetflixACAJudge-v1.0
    stagesEnabled: true
    templatesEnabled: true
    showAllConfigsEnabled: true
  webhook:
    trust:
      enabled: false
